### PR TITLE
add willCall method for remocking

### LINKED ISSUE #5: Feature Request
We were hoping to use this library as default mocking lib for `vitest`, but it lacks some features, since we wanted to make jest compatible wrapper. Is it possible to add this features without making the lib much larger?

- getter/setter support
- distinguishing between return/throw (rn throw just stores as `undefined` or wont even be added if `cb` throws)
- an api to replace mock with another one (questionable, since we can do this inside our own wrapper)

### PR DESCRIPTION
**Pull request by instant1100**
resolve #5

### CODE REVIEW

**Comment by ai** [comment]
`willCall` doesn’t look as a very clear name for me. Do we have any alternatives?

@sheremet-va where did you take this name for your code example in issue? Do they have any explanation why they use it.

**Comment by sheremet-va** [comment]
> `willCall` doesn’t look as a very clear name for me. Do we have any alternatives?
> 
> @sheremet-va where did you take this name for your code example in issue? Do they have any explanation why they use it.

`willCall` is reimagend `callsFake` name from `sinon`. The idea is the same: `mock.willCall(this implementation)` or `mock.callsFake(implementation)`. We implemented it in `tinyspy` as `willCall`.

**Comment by ai** [comment]
@sheremet-va Thanks. I am worry about future form of `will`.

@instant1100 what do you think of `onCall` name? It will explain that we define callback on function call (like `onClick`) and it will be more clear.

**Comment by instant1100** [comment]
@ai it seems good name.  I have just checked implementation in tinyspy. They reset only callback, not callCount, results etc... I think i should fix it too

**Comment by ai** [comment]
> They reset only callback, not callCount, results etc... I think i should fix it too

Yeap, let’s change change function body.

**Comment by ai** [comment]
We also need to add docs (I think a separated section is better)

**Comment by ai** [comment]
I fixed types (re-mock now inherit previous mock’s types) and fix ESLint errors e1dacf4

**Comment by ai** [comment]
@instant1100 do you have Twitter to mention you in release tweet?

**Comment by instant1100** [comment]
@ai yes, but i don't use it and don't remember password.

**Pull request merged**
